### ISSUE TITLE
Crashes when attacking anything with Create 0.5.1

### ISSUE THREAD

**Issue by MrFastZombie** [SammySemicolon/Malum-Mod#181]
Forge 40.2.4
Malum 1.18.2-1.4.4.3
Lodestone 1.18.2-1.3

Attacking any mobs after updating create makes the game crash. 

Steps to reproduce:
1. Load a minecraft world
2. Attack something
3. Crash

```
---- Minecraft Crash Report ----
// My bad.
Time: 5/25/23, 9:29 PM
Description: Ticking player
[java.lang.NoClassDefFoundError:](http://java.lang.noclassdeffounderror/) com/simibubi/create/content/curiosities/weapons/PotatoProjectileEntity
	at [com.sammy.malum.compability.create.CreateCompat$LoadedOnly.convertCaramelToMagicDamage](http://com.sammy.malum.compability.create.createcompat%24loadedonly.convertcarameltomagicdamage/)(CreateCompat.java:25) ~[malum-1.18.2-[1.4.4.3](http://1.4.4.3/).jar%2399!/:1.18.2-[1.4.4.3](http://1.4.4.3/)] {re:classloading}
```

https://mclo.gs/FP536d5

**Comment by SammySemicolon** [comment]
Crying. I will fix soon.

**Comment by Shibva** [comment]
Oh my God, XD

The potato cannon is throwing a noClassDefFound error XD

Out of all the things… It had to be the potato cannon. 

**WEEZE**

**Comment by Shibva** [comment]
OK I think I see what's going on here. I think something may have changed within the canon, caused it to handle custom projectiles differently, or there may have been some sort of change to that class

**Comment by El-Barto-xD** [comment]
Hi,
i found the issue and created a fix based on the 1.4 version.
For which branch would you prefer a PR on?

It really was a change in the class.

**old**
`import com.simibubi.create.content.curiosities.weapons.PotatoProjectileEntity;`

**new**
`import com.simibubi.create.content.equipment.potatoCannon.PotatoProjectileEntity;`

oh yea and ofc a newer version of the mod has to be used as the dependency
`compileOnly fg.deobf("curse.maven:create-328085:4550986")`

this is the newest version of the create mod (v0.5.1b)

Seems like simply changing this would break compatibilty for older create versions, right?

(Sorry im completely new to modding and only wanted to fix this bug since i play with some friends on a server and want to use the new create version lmao)

**Comment by SammySemicolon** [comment]
Yeah, the change is simple enough. You can pr it in to 1.5-1.18.2

**Comment by Shibva** [comment]
probs should let the guys that made the quilt fork for Malum know about this change
might also apply when fabric team finishes and pushers 5.1 on fabric
