### ISSUE TITLE
1.18.2 Server crash when any entity (mob or item) enters void conduit

### ISSUE THREAD

**Issue by zinerith** [SammySemicolon/Malum-Mod#192]
[crash-2023-07-04_05.10.04-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/11944715/crash-2023-07-04_05.10.04-server.txt)
Tried toggling the particle setting in lodestone config, does nothing. Would like some insight, having issues troubleshooting since the only thing we've found that fixes it is removing Malum from the server (and we'd rather not do that)

**Comment by zinerith** [comment]
I tried looking through the resolved issues, but the only other one that mentions void conduits was closed saying "this issue is the same as the previous one" with no reference to what the previous one would be, nor any other issues mentioning the void conduit.

**Comment by zinerith** [comment]
[lodestone-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/11944883/lodestone-client.txt)
This is the config on both server and client for lodestone (had to change to .txt since github rejects .toml files)

**Comment by zinerith** [comment]
I saw through some other issues that Rubidium was apparently causing the crash. I removed the mod, however, and nothing has changed. Same crash, here is the crashlog: 
[crash-2023-07-04_05.53.33-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/11945018/crash-2023-07-04_05.53.33-server.txt)

**Comment by QinomeD** [comment]
This will be fixed in a patch.

**Comment by AetherBreaker** [comment]
[crash-2023-07-04_21.23.25-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/11952397/crash-2023-07-04_21.23.25-server.txt)
I am also experiencing this exact same issue, my world is currently stuck as anytime I try to connect to my server (and consequently load the chunks where this issue is occuring.) my server crashes. And I don't want to remove this mod and remove all of its worldgen, has anyone found any temporary fix for this until it gets patched.

**Comment by QinomeD** [comment]
No, there isn't, wait for the patch

**Comment by SammySemicolon** [comment]
Fixed in 1.5.0.1
